import {
  collection,
  doc,
  getDocs,
  addDoc,
  updateDoc,
} from 'firebase/firestore'
import { db } from '../../../shared/services/firebaseService'

/**
 * Admin notifications come from three places:
 *  - `notifications/{uid}/items` (notification_items): the per-user inbox that
 *    the announcement fan-out and the project/task triggers write to.
 *  - `organizations/{orgId}/notifications` (org_notifications): org-wide events
 *    such as a won deal.
 *  - `notifications` (app_docs): rows this portal creates itself.
 * The panel previously read only the last one, so nothing generated by the
 * database ever showed up.
 */

const INBOX = 'inbox'
const LEGACY = 'legacy'
const ORG = 'org'

const toIso = (value) => {
  if (!value) return null
  if (typeof value === 'string') return value
  if (typeof value.toDate === 'function') return value.toDate().toISOString()
  if (value.seconds) return new Date(value.seconds * 1000).toISOString()
  return null
}

const normalize = (docSnap, source, ownerUid = null) => {
  const data = docSnap.data() || {}
  return {
    ...data,
    notificationId: docSnap.id,
    isRead: data.isRead === true,
    createdAt: toIso(data.createdAt) || new Date(0).toISOString(),
    link: data.adminLink || data.link || null,
    _source: source,
    _ownerUid: ownerUid,
  }
}

const idList = (userIdOrIds) =>
  [...new Set((Array.isArray(userIdOrIds) ? userIdOrIds : [userIdOrIds]).filter(Boolean).map(String))]

const refFor = (notif) => {
  if (notif._source === INBOX) {
    return doc(db, `notifications/${notif._ownerUid}/items`, notif.notificationId)
  }
  if (notif._source === ORG) {
    return doc(db, `organizations/${notif._ownerUid}/notifications`, notif.notificationId)
  }
  return doc(db, 'notifications', notif.notificationId)
}

/**
 * @param {string[]|string} identityIds - every business id this admin owns
 * @param {string} [orgId]
 */
export const getNotifications = async (identityIds = [], orgId = null) => {
  const ids = idList(identityIds)

  const sources = [
    ...ids.map(async (uid) => {
      const snap = await getDocs(collection(db, `notifications/${uid}/items`))
      return snap.docs.map((d) => normalize(d, INBOX, uid))
    }),
    (async () => {
      const snap = await getDocs(collection(db, 'notifications'))
      return snap.docs.map((d) => normalize(d, LEGACY))
    })(),
  ]

  if (orgId) {
    sources.push(
      (async () => {
        const snap = await getDocs(collection(db, `organizations/${orgId}/notifications`))
        return snap.docs.map((d) => normalize(d, ORG, orgId))
      })()
    )
  }

  const settled = await Promise.allSettled(sources)
  const merged = []
  const seen = new Set()

  for (const result of settled) {
    if (result.status !== 'fulfilled') {
      console.error('Error loading notifications:', result.reason)
      continue
    }
    for (const notif of result.value) {
      // The same trigger payload can land in several identity inboxes.
      const key = notif.tag || `${notif._source}:${notif.notificationId}`
      if (seen.has(key)) continue
      seen.add(key)
      merged.push(notif)
    }
  }

  return merged.sort((a, b) => (a.createdAt < b.createdAt ? 1 : -1))
}

/**
 * @param {object} notif - a notification returned by getNotifications
 */
export const markNotificationReadInDb = async (notif) => {
  try {
    if (!notif?.notificationId) return
    await updateDoc(refFor(notif), {
      isRead: true,
      updatedAt: new Date().toISOString(),
    })
  } catch (err) {
    console.error('Error marking notification as read:', err)
  }
}

export const markAllNotificationsReadInDb = async (notifs = []) => {
  await Promise.allSettled(notifs.map((notif) => markNotificationReadInDb(notif)))
}

export const createNotification = async (notifData) => {
  try {
    const docRef = await addDoc(collection(db, 'notifications'), {
      ...notifData,
      isRead: false,
      createdAt: new Date().toISOString(),
    })
    return { notificationId: docRef.id, ...notifData }
  } catch (err) {
    console.error('Error creating notification in Firestore:', err)
    return { notificationId: `notif_${Date.now()}`, ...notifData }
  }
}
